# opnrvn-r-109
ruleId: gcp-management-tools-ensure-log-metric-filter-and-alerts-exist-for-sql-instance-config-changes
type: asset
ruleName: >
  Ensure that the log metric filter and alerts exist for SQL instance configuration changes
description: >
  Monitoring changes to SQL instance configuration changes may reduce the time needed to detect and correct misconfigurations done on the SQL server.
severity: high
enabled: true
sql: >
  SELECT 'No log metric filter and alerts exist for SQL instance configuration changes' AS assetid
    WHERE NOT EXISTS (
        SELECT acc.assetid
          FROM ${magpie_schema}.gcploggingmetric acc
         WHERE resourcetype = 'GCP::Logging::Metric'
           AND regexp_replace(acc."configuration" ->> 'filter_', E'[\\n\\r\\f\\u000B\\u0085\\u2028\\u2029]+', ' ', 'g') =
               'protoPayload.methodName="cloudsql.instances.update"'
           AND EXISTS (
                SELECT alrt.assetid, metric
                  FROM ${magpie_schema}.gcpmonitoringalertpolicy alrt,
                LATERAL (
                      SELECT value -> 'condition_' ->> 'filter_' as metric
                      FROM jsonb_array_elements(alrt.configuration -> 'conditions_')
                ) arr
                 WHERE alrt.resourcetype = 'GCP::Monitoring::AlertPolicy'
                   AND alrt."configuration" -> 'enabled_' ->> 'value_' = 'true'
                   AND metric ILIKE '%'||acc.assetid||'%'
           )
    )
remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 0.9